spring.application.name=liquibase-lab

spring.datasource.url=jdbc:mysql://localhost:3306/liquibase_lab
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml