spring.application.name=redis-cache-lab

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.type=redis
spring.cache.redis.time-to-live=60s
spring.cache.redis.cache-null-values=false