spring.application.name=flight-archive-postgresql-lab
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/flight_archive_lab
spring.datasource.username=alikaracor
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

spring.kafka.consumer.group-id=flight-archive-postgresql-lab-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.alikaracor.learning.flightarchivepostgresqllab.event

app.kafka.flight-events-topic=flight.events

management.endpoints.web.exposure.include=health,info
